pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    // Установка зависимостей из файла requirements.txt
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Python Scripts') {
            steps {
                script {
                    echo 'Running Python scripts...'

                    sh 'python3 scripts/data_creation.py'
                    echo 'Finished running data creation'

                    sh 'python3 scripts/model_preprocessing.py'
                    echo 'Finished running model preprocessing'

                    sh 'python3 scripts/model_preparation.py'
                    echo 'Finished running model preparation'

                    sh 'python3 scripts/model_testing.py'
                    echo 'Finished running model testing'

                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}